version: "3.6"

networks:
  development:

services:
  redis1:
    image: redis:alpine
    restart: always
    ports:
      - "2137:6379"
    networks:
      - development
  redis2:
    image: redis:alpine
    restart: always
    ports:
      - "2138:6379"
    networks:
      - development
  redis-cluster:
    image: md03/redis-cluster
    restart: always
    ports:
      - "6000:6000"
      - "6001:6001"
      - "6002:6002"
      - "6003:6003"
      - "6004:6004"
      - "6005:6005"
