name: testing-cassandra
on: 
  push:
    paths: 
      - 'packages/cassandra/**'
      
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/cassandra
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
        
      - name: Run docker-compose
        run: docker compose up -d
        
      - name: Wait for database startup
        run: sleep 100
        
      - name: Install packages with pnpm
        run: pnpm install --frozen-lockfile
        
      - name: Run lint
        run: pnpm lint
        
      - name: Run tests
        run: pnpm test
        
      - name: Close docker-compose
        run: docker compose down -v
