name: testing-redis
on: 
  push:
    paths: 
      - 'packages/redis/**'
      
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/redis
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        
      - name: Make script executable
        run: chmod +x ./scripts/create-cluster.sh
        
      - name: Run docker-compose
        run: docker compose up -d
        
      - name: Wait for cluster
        run: sleep 5
        
      - name: Install packages with pnpm
        run: pnpm install --frozen-lockfile
        
      - name: Run lint checks
        run: pnpm lint
        
      - name: Run tests
        run: pnpm test
        
      - name: Close docker-compose
        run: docker compose down -v
